---
- name: Copy the host.xml template
  template: src={{ template_file }} dest=/opt/wildfly-9.0.2.Final/domain/configuration/host.xml
  register: result

- name: Mark node with changed configuration
  set_fact:
    node_restart: true
  when: result.changed
